name: SpellCheck
on: push
jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
      - name: 🚧　Install
        run: |
          yarn install
      - name: 📦　Build
        run: |
          yarn build
#      - name: 🔑　Generate Token
#        uses: wow-actions/use-app-token@v2
#        with:
#          app_id: ${{ secrets.APP_ID }}
#          private_key: ${{ secrets.PRIVATE_KEY }}
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          include: |
            **.md
            **.txt
